imap:
    servers:
        - name: "ExampleIMAP"
          host: mail.example.com
          port: 993
          username: test@example.com
          password: supersecret

webmail:
    servers:
        - name: "ExampleWebmail"
          type: "roundcube"
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
          base_url: "https://webmail.example.com"
          username: test@example.com
          password: supersecret

metrics:
    prometheus_port: 9090
    test_interval: 30
